### ISSUE TITLE
Incompatibility with compose-cli 2.0.0-rc1

### ISSUE THREAD

**Issue by mdantonio** [gabrieldemarmiesse/python-on-whales#234]
Hello,
after upgrading compose-cli 2.0.0 from beta6 to rc1 I started to get the following error:

```
* 'Deploy.Resources.Reservations.cpus' expected type 'string', got unconvertible type 'float64', value: '0.25'
```

So I changed my .yml by replacing:

```
services:
  myservice:
    deploy:
      resources:
        reservations:
          cpus: 0.25
```

with:

```
services:
  myservice:
    deploy:
      resources:
        reservations:
          cpus: "0.25"
```

This silenced the error on compose-cli, but now is python on whales that is complaining about the expected type:

```
pydantic.error_wrappers.ValidationError: 18 validation errors for ComposeConfig
services -> myservice -> deploy -> resources -> reservations -> cpus
  value is not a valid float (type=type_error.float) 
```

I didn't find any reference to this type change in the changelog of compose-cli rc1 so I'm not totally sure if this is a feature that should be supported by python on whales or a bug that should be reported on compose cli
