### ISSUE TITLE
Avoid mutable objects within parameter default value expression

### ISSUE THREAD

**Issue by rafrafek** [gabrieldemarmiesse/python-on-whales#398]
I've noticed that in some places like here: https://github.com/gabrieldemarmiesse/python-on-whales/blob/1519e00f12963d40d2297afdbe1d1e9f8bae3fcc/python_on_whales/utils.py#L82 there are default values that are mutable. It may lead to very strange bugs, see:

https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/

Please consider using `flake8-bugbear` to catch errors like this.

Or for VS Code:

```toml
[tool.pyright]
# This is specific to pyright or VS Code (Pylance) users
reportCallInDefaultInitializer = true
```

With the setting above and type checking set to "strict" VS Code can catch some nasty bugs even in projects like this, where the code is already well written. In other projects everything flashes in red 😅
