### ISSUE TITLE
Docker run() - volumes don't work as in docker compose

### ISSUE THREAD

**Issue by radovansliz** [gabrieldemarmiesse/python-on-whales#425]
Hello,
I have a python project where I use docker.run(). It is a postgresql container where I defined volumes to run .sql files on startup. It looks like this:
```
[
        (
            pathlib.Path("folder1/folder2/database-data").absolute(),
            "/var/lib/postgresql/data",
        ),
        (
            pathlib.Path("folder1/folder2/folder3/create_tables.sql").absolute(),
            "/docker-entrypoint-initdb.d/create_tables.sql",
        ),
        (
            pathlib.Path("folder1/folder2/folder3/insert_data.sql").absolute(),
            "/docker-entrypoint-initdb.d/insert_data.sql",
        ),
    ]
```
When the container is up, it will not execute these .sql files.I checked and found that there is insert_data.sql (or create_table.sql) in docker-entrypoint-inidb.d but as a folder not as a file to run. But if I tried to run it manually using docker-compose which looks like this:
```
database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresqk/data
    volumes:
      - ./database-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./folder3/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./folder3/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
    ports:
      - "6544:5432"
```
It works correctly. Couldn't there be a problem with the  .run() volume attribute or is my definition of volumes in docker.run() is incorrect?
